server:
  env: public
  addr: 0.0.0.0:8081
  read-timeout: 10
  write-timeout: 10
  max-header-bytes: 1048576
database:
  type: mysql
  hostname: 192.168.5.48
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: library
  username: library-admin
  password: libraryadmin888
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: false
  log-zap: ""
redis:
  db: 0
  addr: 192.168.5.48:6379
  password: "123456"
  max-idle: 10
  max-active: 10
  idle-timeout: 6
  wait: true
jwt:
  signing-key: 649547eab943aabadf02db3dd9fa53db
  expires-time: 86400
zap:
  level: info
  encodelevel: CapitalLevelEncoder
  director: /var/www/html/lemon-gin-web-framework/runtime/log
  max-size: 1
  max-backups: 5
  max-age: 30
  compress: false

