server:
  env: public
  addr: 8081
  read-timeout: 10
  write-timeout: 10
  max-header-bytes: 1048576
mysql:
  path: 127.0.0.1:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gva
  username: root
  password: tanwan888
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: false
  log-zap: ""
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
